### PR TITLE
Maroon-498 [PointWave] Fix reset behavior and sliders

### LINKED ISSUE #498: [PointWave] Reset button does not work after manually changing position of source
**Describe the defect**
The waves in the PointWave experiment do not originate from the source under certain preconditions (see next section)

**To Reproduce**
1. Go to PointWave experiment
2. Click on 'Add Source'
3. Move source with the mouse to somewhere, e.g. middle of the experiment water pool
4. In the top right, change source position to something different, e.g. 1.00 & 1.00
5. Click on the double arrow back (reset simulation button, to the left of the play button)
6. Source now appears to move to the previous position where it has been dragged to with the mouse, but if you now press 'Play', the waves originate from the manual position that was in the top right corner for example

**Expected behavior**
Not sure how the experiment was intended to work, either I expect all sources to be deleted anyway, or if the previous mouse position really is to be used, then the waves should also originate from that position.

**Found in version**
develop branch, 92fd345af91c50cc60a2a71873018b66615f23a4

**Screenshots**
waves do not originate from the source, but from the position where the source was before pressing the reset simulation button
grafik

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Additional context**
-

### PR DESCRIPTION
**Pull request by FlorianGlawogger**
Fix #498 

- Resetting point wave experiment now clears all wave sources
- Resetting point wave experiment also resets the x/z coordinates and add/delete source button UI elements
- When starting or resetting the experiment, the wave peak/trough color sliders are now set correctly

### CODE REVIEW

File: unity/Assets/Maroon/scenes/experiments/PointWave/scripts/PointWavePoolHandler.cs [hunk 1]
```diff
@@ -201,6 +201,7 @@ public void RemoveSource(PointWaveSource source)
 
     public void ResetObject()
     {
+        ResetWholeObject();
```
Comment (michaelholly) [inline unity/Assets/Maroon/scenes/experiments/PointWave/scripts/PointWavePoolHandler.cs]: Should we move the code from the ResetWholeObject method to ResetObject instead of calling ResetWholeObject, or is ResetWholeObject used somewhere?

**Review by michaelholly — CHANGES_REQUESTED** [review]

**Review by michaelholly — APPROVED** [review]
