### PR TITLE
defect/Maroon-387-AudioBarIsntSetToFullAtTheBeginning: fixed audio settings menu

### LINKED ISSUE #387: Audio Bar Isn't Set to Full In The Beginning
**Describe the defect**
When a user enters to simulation, the audio bar should be set to max but the audio settings are showing that there is no audio initially. However, there is.

**To Reproduce**
1. Go to lab
2. Observe sounds
3. Check the audio setting by pressing "ESC" button.
4. See that, the audio bar is set to zero.

**Expected behavior**
Initial audio bar should be set to max since there is already a sound.

**Found in version**
The version where the defect was detected v4.2 -> build: 20211213

**Screenshots**
afterentrance

**WebGL(please complete the following information):**
OS: Windows 10, 21H2 Build: 19044.1415
Browser: Chrome
Version 97.0.4692.71

Additional Notes:
If one may change the audio setting in the simulation from it's initial state to max, the sound will stay the same. However, after that point, if one may change to minimum, the settings will work as it is intended.

### PR DESCRIPTION
**Pull request by yavin87**
Closes #387

See comments under `Files changed`

### CODE REVIEW

File: unity/Assets/Maroon/GlobalEntities/SoundManager/SoundManager.cs [hunk 1]
```diff
@@ -66,6 +66,14 @@ public class SoundManager : MonoBehaviour, GlobalEntity
         public static SoundManager Instance => SoundManager._instance;
         MonoBehaviour GlobalEntity.Instance => Instance;
 
+        // -------------------------------------------------------------------------------------------------------------
+        // Audio sources
+        
+        /// <summary>
+        ///     Getter for Sound Effect AudioSource component
+        /// </summary>
+        public AudioSource soundEffectSource => _soundEffectSource;
```
Comment (yavin87) [inline unity/Assets/Maroon/GlobalEntities/SoundManager/SoundManager.cs:75]: Added a getter to access SoundManager's sound effect AudioSource component from other prefabs to unify all sound effects to one source.

File: unity/Assets/Maroon/GlobalEntities/SoundManager/SoundManager.cs [hunk 2]
```diff
@@ -118,9 +126,6 @@ private void Awake()
 
             // Keep alive
             DontDestroyOnLoad(this.gameObject);
-
-            // TODO: Cleanup
-            _musicSource = GetComponent<AudioSource>();
```
Comment (yavin87) [inline unity/Assets/Maroon/GlobalEntities/SoundManager/SoundManager.cs:123]: AudioSources are already assigned in prefab via Inspector. Calling GetComponent when multiple Components of a type are available is ambiguous.

File: unity/Assets/Maroon/SharedEntities/Player/ModeFirstPerson/ModeFirstPerson.cs [hunk 3]
```diff
@@ -111,7 +113,7 @@ public float RotationMultiplier
     const float k_JumpGroundingPreventionTime = 0.2f;
     const float k_GroundCheckDistanceInAir = 0.07f;
 
-    void Start()
+    IEnumerator Start()
```
Comment (yavin87) [inline unity/Assets/Maroon/SharedEntities/Player/ModeFirstPerson/ModeFirstPerson.cs:116]: Changed return type to allow WaitUntil

File: unity/Assets/Maroon/SharedEntities/Player/ModeFirstPerson/ModeFirstPerson.cs [hunk 4]
```diff
@@ -1,14 +1,16 @@
-﻿using UnityEngine;
+﻿using System.Collections;
+using Maroon.GlobalEntities;
+using UnityEngine;
 using UnityEngine.Events;
 
-[RequireComponent(typeof(CharacterController), typeof(ModeFirstPersonInputHandler), typeof(AudioSource))]
+[RequireComponent(typeof(CharacterController), typeof(ModeFirstPersonInputHandler))]
```
Comment (yavin87) [inline unity/Assets/Maroon/SharedEntities/Player/ModeFirstPerson/ModeFirstPerson.cs:6]: Removed AudioSource component from Prefab

File: unity/Assets/Maroon/SharedEntities/Player/ModeFirstPerson/ModeFirstPerson.cs [hunk 5]
```diff
@@ -1,14 +1,16 @@
...
 public class ModeFirstPerson : MonoBehaviour
 {
     [Header("References")]
     [Tooltip("Reference to the main camera used for the player")]
     public Camera playerCamera;
     [Tooltip("Audio source for footsteps, jump, etc...")]
-    public AudioSource audioSource;
+    private AudioSource audioSource;
```
Comment (yavin87) [inline unity/Assets/Maroon/SharedEntities/Player/ModeFirstPerson/ModeFirstPerson.cs:13]: Set to private, since it's not accessed by Inspector anymore and only used inside this class.

File: unity/Assets/Maroon/SharedEntities/Player/ModeFirstPerson/ModeFirstPerson.cs [hunk 6]
```diff
@@ -123,6 +125,10 @@ void Start()
         // force the crouch state to false when starting
         SetCrouchingState(false, true);
         UpdateCharacterHeight(true);
+
+        // Wait for SoundManager to be instantiated, then get its soundEffect AudioSource
+        yield return new WaitUntil(() => SoundManager.Instance != null);
+        audioSource = SoundManager.Instance.soundEffectSource;
```
Comment (yavin87) [inline unity/Assets/Maroon/SharedEntities/Player/ModeFirstPerson/ModeFirstPerson.cs:131]: Get the audioSource component from global SoundManager. Just in case, wait for it to be instantiated first.

File: unity/Assets/Maroon/SharedEntities/Player/ModeFirstPerson/ModeFirstPerson.prefab [hunk 7]
```diff
@@ -62,7 +62,6 @@ GameObject:
   - component: {fileID: 411276125901475930}
   - component: {fileID: 9005581280146270069}
   - component: {fileID: 3418080945172443874}
-  - component: {fileID: 3846857389753723001}
```
Comment (yavin87) [inline unity/Assets/Maroon/SharedEntities/Player/ModeFirstPerson/ModeFirstPerson.prefab:65]: Removed AudioSource component from prefab

File: unity/Assets/Maroon/SharedEntities/Player/ModeFirstPerson/ModeFirstPerson.prefab [hunk 8]
```diff
@@ -115,7 +114,6 @@ MonoBehaviour:
   m_Name: 
   m_EditorClassIdentifier: 
   playerCamera: {fileID: 6318173596315821001}
-  audioSource: {fileID: 3846857389753723001}
```
Comment (yavin87) [inline unity/Assets/Maroon/SharedEntities/Player/ModeFirstPerson/ModeFirstPerson.prefab:118]: Removed reference on its own AudioSource component

File: unity/Assets/Maroon/SharedEntities/Player/ModeFirstPerson/ModeFirstPerson.prefab [hunk 9]
```diff
@@ -164,102 +162,6 @@ CharacterController:
...
-      value: 1
-      inSlope: 0
-      outSlope: 0
-      tangentMode: 0
-      weightedMode: 0
-      inWeight: 0.33333334
-      outWeight: 0.33333334
-    m_PreInfinity: 2
-    m_PostInfinity: 2
-    m_RotationOrder: 4
```
Comment (yavin87) [inline unity/Assets/Maroon/SharedEntities/Player/ModeFirstPerson/ModeFirstPerson.prefab:262]: Removed AudioSource component from prefab. Verified that SoundManager's soundFX AudioSource has the same settings.

File: unity/Assets/Maroon/reusableGui/Menu/PrefabsColumns/scrMenuColumnAudio.cs [hunk 10]
```diff
@@ -20,18 +20,20 @@ public class scrMenuColumnAudio : MonoBehaviour
...
     {
-        // Listen to music slider
+        // Apply initial slider value from Music AudioSource and listen to music slider
         if (_musicSlider)
         {
-            _musicSlider.GetComponent<Slider>().onValueChanged
-                .AddListener((value) => this.OnChangeMusicSlider(value));
+            var musicSliderComponent = _musicSlider.GetComponent<Slider>();
+            musicSliderComponent.value = SoundManager.Instance.MusicVolume;
+            musicSliderComponent.onValueChanged.AddListener(this.OnChangeMusicSlider);
```
Comment (yavin87) [inline unity/Assets/Maroon/reusableGui/Menu/PrefabsColumns/scrMenuColumnAudio.cs:28]: Music: Set initial slider value to its AudioSource's volume before adding the listener as before.

File: unity/Assets/Maroon/reusableGui/Menu/PrefabsColumns/scrMenuColumnAudio.cs [hunk 11]
```diff
@@ -20,18 +20,20 @@ public class scrMenuColumnAudio : MonoBehaviour
...
-        // Listen to sound effect slider
+        
+        // Apply initial slider value from Sound Effect AudioSource and listen to sound effect slider
         if (_soundEffectSlider)
         {
-            _soundEffectSlider.GetComponent<Slider>().onValueChanged
-                .AddListener((value) => this.OnChangeSoundEffectSlider(value));
+            var soundEffectSliderComponent = _soundEffectSlider.GetComponent<Slider>();
+            soundEffectSliderComponent.value = SoundManager.Instance.SoundEffectVolume;
+            soundEffectSliderComponent.onValueChanged.AddListener(this.OnChangeSoundEffectSlider);
```
Comment (yavin87) [inline unity/Assets/Maroon/reusableGui/Menu/PrefabsColumns/scrMenuColumnAudio.cs:36]: SoundFX: Set initial slider value to its AudioSource's volume before adding the listener as before.

**Review by michaelholly — APPROVED** [review]
